---
date-format: "YYYY-MM-DD hh:mm:ss"
date: today
published-title: "Report Created"
params:
  # A value that can be `S7::convert`'ed into a `val.meter::pkg`
  # 
  # Common inputs include:
  #
  #   - DESCRIPTION (or PACKAGES) file string
  #   - PACKAGES file string
  #   - a package name (to be sourced from a repository)
  #   - a list of package metadata and metrics
  #   - an Rds file generated from a val.meter::pkg object
  #
  package: NULL
  
  # Additional options to set during evaluation.
  #
  # These may be especially useful if the report is used for performing package
  # evaluations, in which case you may consider passing `?val.meter::options` to
  # enable addition evaluation permissions.
  #
  # To set options using R code, pass a string prefixed with "!expr".
  #
  options: NULL
  
  # Session info to attach to the report
  #
  # When empty, defaults to `val.report::session()` captured during report
  # generation. If you wish to provide information captured from previous
  # execution, provide `val.report::session()` from that session as a parameter.
  #
  session: NULL
  
  image: "rocker/rver"
  hide_reverse_deps: true
format:
  html: 
    toc: true  
    embed-resources: true
    include-in-header: "top_page.html"
    include-after-body: "transform_pre_class.html"
    theme: 
      dark: [darkly, custom.scss]
      light: [default, custom.scss, custom_light.scss]
  gfm:
    html-math-method: webtex    
  typst:
    toc: true
    section-numbering: 1.1.1
    df-print: default
    margin:
      x: 2cm
      y: 2cm
filters:
  - foldable_code.lua
---

```{r setup, include = FALSE}
options(
  width = 80L, 
  covr.record_tests = TRUE
)

knitr::opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  error = TRUE,
  cache = FALSE
)

library(S7)
library(tools)
library(knitr)
library(val.meter)
library(val.report)

header <- val.report::knitr_mutable_header()
log <- val.report::knitr_logger()
```

# Context

```{r loading, include = FALSE}
if (is.null(params$package)) {
  stop(
    "The `package` parameter is required. At a minimum pass a package ",
    "name, which will be discovered from installed packages or sourced from a ",
    "repository. For details, see `?val.report::report()`."
  )
}

# parse options, handling expression strings
opts <- knitr_update_options(params$options)
log("parsed `params$options` as:\n", opts, "\n\n")

# parse provided parameter session info or default to current session
session <- params$session %||% val.report::session()
log(
  "using ", if (is.null(params$session)) "current" else "param", 
  " session captured at: ", format(as.POSIXct(session$time)), "\n\n"
)

# derive a package object from parameter value
pkg <- convert(params$package, val.meter::pkg)
log("parsed `params$package` into pkg from:\n", pkg@resource, "\n\n")

# calculate package metrics
met <- metrics(pkg)
log("evaluated metrics:\n", met, "\n\n")

header$title <- paste0(pkg$name, " (v", pkg$version, ")")
```

## Package `R CMD check`

_The following metrics are derived from the `val.meter` R package._

::: {.content-visible when-format="html"}
::: {.callout-note appearance="minimal" collapse="true" title="R CMD check summary"}
```{r r_cmd_check_results, results = 'asis'}
library(rcmdcheck)
options(width = 80L, crayon.enabled = TRUE, cli.ansi = TRUE)
htmltools::tags$div(
  style = cli::ansi_html_style(colors = 8L),
  htmltools::tags$pre(htmltools::HTML(cli::ansi_html(paste(capture.output(pkg$r_cmd_check), collapse = "\n"))))
)
```
:::

::: {.callout-note appearance="minimal" collapse="true" title="R CMD check execution logs"}
```{r r_cmd_check_html}
if (!is.null(log <- pkg@logs[["r_cmd_check"]])) {
  format(log, style = "html")
}
```
:::
:::

::: {.content-hidden when-format="html"}
```{r r_cmd_check_text, results = 'asis'}
cat(format(pkg@logs[["r_cmd_check"]], style = "text"), "\n")
```
:::

## System Info

```{r execution_info}
#| tab.cap: "**System information**. Table about the system used to check the package."

tt_sys_info_df <- data.frame(
  Field = c("OS", "Platform", "System", "R Version", "Execution Time"),
  Value = c(
    session$session_info$running,
    session$r_version$platform,
    session$r_version$system,
    session$r_version$version.string,
    format(as.POSIXct(session$time), tz = "UTC", usetz = TRUE)
  )
)

knitr::kable(tt_sys_info_df)
```

<!--
From here we use the lua filter based on this issue from Quarto itself
https://github.com/quarto-dev/quarto-cli/issues/341
Please take into account that not all content in the chunks will be correctly folded
- character vectors are
- reactable tables are not
An alternative is to use callout blocks with collapse = TRUE
The advantage of the foldable_code lua filter is that the code is printed exactly as in the R console
-->

## R Session Info

```{r session_info, attr.output='.details summary="Session info"'}
session$session_info
```

```{r Platform, attr.output='.details summary="Platform"'}
unlist(session$platform)
```

```{r capabilities, attr.output='.details summary="R\'s capabilities"'}
unlist(session$capabilities)
```

```{r external-software, attr.output='.details summary="External software"'}
unlist(session$external_software)
```

```{r graphic-software, attr.output='.details summary="External graphics software"'}
unlist(session$graphics_software)
```

```{r machine, attr.output='.details summary="Numerical characteristics of the machine"'}
unlist(session$machine)
```

```{r RNGKind, attr.output='.details summary="Random number generation process"'}
session$rng_kind
```

## Information about the environment

Environment variables and R options affect how package checks and software in it
might behave.

```{r computing, attr.output='.details summary="Environment variables when running this report"'}
val.report::environ_report(exclude = c("APPDATA", "GITHUB", "GITHUB_PAT", "GITHUB_PAT_GITHUB_COM", 
                                       "GITLAB", "GITLAB_PAT", "ProgramFiles", "ProgramFiles(x86)", 
                                       "R_DptShare", "R_USER", "USERDNSDOMAIN", "USERDOMAIN", "USERDOMAIN_ROAMINGPROFILE", 
                                       "USERNAME", "USERPROFILE"))
```

```{r options, attr.output='.details summary="These are the options set to generate the report"'}
val.report::options_report(exclude = c("usethis.full_name", "usethis.description", "usethis.destdir"))
```
