---
title: "riskmetric_scores"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{riskmetric_scores}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library("val.report")
```

We generate the assessment with riskmetric and we load it as part of the report:

```{r, eval = file.exists("inst/assessments/dplyr.rds")}
dplyr_assessment <- readRDS("assessments/dplyr.rds")
```

Then we can start working on the assessment. 
This is not a quantification of a risk like `riskmetric::pkg_score()` but some minor conversion to a value of length 1, one character or one numeric value. 

```{r}
list.files("assessments", full.names = TRUE)
knitr::knit_exit()
# riskmetric_a <- assessment(riskmetric_assessment)
# dplyr_a <- assessment(dplyr_assessment)

# dplyr_a
# riskmetric_a
```


This is different from the scores, such as the ones [previously used](https://github.com/pharmaR/repos/blob/main/ubuntu-22.04/4.4/riskscore/src/contrib/PACKAGES).

```{r}
download.file("https://raw.githubusercontent.com/pharmaR/repos/refs/heads/main/ubuntu-22.04/4.4/riskscore/src/contrib/PACKAGES?token=GHSAT0AAAAAACZC3CYXK3Q62EBLVXQH5CHSZZ7I2BA",
              destfile = "inst/source/UBUNTU-PACKAGES")
```


